spring:
  datasource:
#    url: jdbc:postgresql://localhost/postgres
#    username: postgres
#    password: dalin.ean
#    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 500000MB
      max-file-size: 800000MB
      max-request-size: 700000MB

mybatis:
  type-aliases-package: com.estock.api.dto
  config-location: classpath:mybatis/mybatis_config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml