spring:
  datasource:
    url: jdbc:postgresql://45.32.116.206:5432/postgres
    username: postgres
    password: kheang
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 500000MB
      max-file-size: 800000MB
      max-request-size: 700000MB

mybatis:
  type-aliases-package: com.api.stockmanagement.provider,com.api.stockmanagement.common.dto
  config-location: classpath:mybatis/mybatis_config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml